import XCTest

@testable import AdventOfCode

final class Day11Tests: XCTestCase {
    let testData1 = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """

    let testData2 = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """
    
    func testPart1() throws {
        let challenge = Day11(data: testData1)
        XCTAssertEqual(String(describing: challenge.part1()), "374")
    }
    
    func testPart2() throws {
        let challenge = Day11(data: testData2)
        XCTAssertEqual(String(describing: challenge.part2()), "82000210")
    }
}
